workflows:
  flutter-workflow:
    name: Flutter Workdlow
    environment:
      java: 11
      flutter: 3.3.4

    instance_type: mac_mini_m2
    scripts:
      - flutter pub get
      - flutter clean
      - flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          # - devalenya@gmail.com
          - sargrace7@gmail.com
        notify:
          success: true
          failure: false
     # google_play:
       # credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
       # track: $GOOGLE_PLAY_TRACK
        #submit_as_draft: true
